"use server"

import JSZip from "jszip"
import type { AgentConfig } from "./types"
import { generateCDCAgentCode, generateOrcaAgentCode } from "./agent-utils"


export async function deployCDCAgent(agentId: string, config: AgentConfig) {
    try {
        console.log(`\n[0rca-Deployer] Start CDC Agent: ${agentId}`)

        // 1. Generate agent.py
        const agentCode = generateCDCAgentCode(agentId, config)

        // 2. Create Zip
        const zip = new JSZip()
        zip.file("agent.py", agentCode)

        let requirements = `orca-network-sdk>=1.0.5\npython-dotenv\ncrypto-com-agent-client\n`
        zip.file("requirements.txt", requirements)
        zip.file(".env", "# Generated by 0rca-pod-v2\n")
        zip.file("Procfile", "web: python agent.py\n")

        const zipBlob = await zip.generateAsync({ type: "uint8array" })

        // 3. Prepare Deployment
        const DEPLOYER_URL = "https://deploy.0rca.live/deploy"
        const DEPLOYER_TOKEN = process.env.DEPLOYER_SERVICE_TOKEN || "orca_test_token_12345"

        const formData = new FormData()
        const zipFile = new Blob([zipBlob as any], { type: 'application/zip' })
        formData.append('file', zipFile, 'agent.zip')
        formData.append('agentId', agentId)

        const envVars = [
            { key: 'GOOGLE_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'GEMINI_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'CDC_API_KEY', value: config.cdcApiKey },
            { key: 'CDC_PRIVATE_KEY', value: config.cdcPrivateKey },
            { key: 'ORCA_NETWORK', value: 'mainnet' }
        ].filter(v => v.value);

        formData.append('envVars', JSON.stringify(envVars))

        const response = await fetch(DEPLOYER_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${DEPLOYER_TOKEN}`
            },
            body: formData
        })

        if (!response.ok) {
            const errorText = await response.text()
            throw new Error(`Deployer error: ${errorText}`)
        }

        const result = await response.json()
        return { success: true, ...result }

    } catch (error: any) {
        console.error("[0rca-Deployer] Critical Failure:", error.message)
        return { success: false, error: error.message }
    }
}

export async function deployOrcaAgent(agentId: string, config: AgentConfig) {
    try {
        console.log(`\n[0rca-Deployer] Start Orca Agent: ${agentId}`)

        // 1. Generate agent.py
        const agentCode = generateOrcaAgentCode(agentId, config)

        // 2. Create Zip
        const zip = new JSZip()
        zip.file("agent.py", agentCode)

        let requirements = `orca-network-sdk>=1.1.0\npython-dotenv\n`
        if (config.crewAITools && config.crewAITools.length > 0) {
            requirements += `crewai\ncrewai_tools\n`
        }
        zip.file("requirements.txt", requirements)
        zip.file(".env", "# Generated by 0rca-pod-v2\n")
        zip.file("Procfile", "web: python agent.py\n")

        const zipBlob = await zip.generateAsync({ type: "uint8array" })

        // 3. Prepare Deployment
        const DEPLOYER_URL = "https://deploy.0rca.live/deploy"
        const DEPLOYER_TOKEN = process.env.DEPLOYER_SERVICE_TOKEN || "orca_test_token_12345"

        const formData = new FormData()
        const zipFile = new Blob([zipBlob as any], { type: 'application/zip' })
        formData.append('file', zipFile, 'agent.zip')
        formData.append('agentId', agentId)

        const envVars = [
            { key: 'GOOGLE_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'GEMINI_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'ORCA_NETWORK', value: 'mainnet' }
        ].filter(v => v.value);

        formData.append('envVars', JSON.stringify(envVars))

        const response = await fetch(DEPLOYER_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${DEPLOYER_TOKEN}`
            },
            body: formData
        })

        if (!response.ok) {
            const errorText = await response.text()
            throw new Error(`Deployer error: ${errorText}`)
        }

        const result = await response.json()
        return { success: true, ...result }

    } catch (error: any) {
        console.error("[0rca-Deployer] Critical Failure:", error.message)
        return { success: false, error: error.message }
    }
}

export async function importGithubAgent(agentId: string, repoUrl: string, branch: string = 'main') {
    try {
        console.log(`\n[0rca-Deployer] Start GitHub Import: ${agentId} from ${repoUrl}`);

        const DEPLOYER_URL = "https://deploy.0rca.live/github/import";
        const DEPLOYER_TOKEN = process.env.DEPLOYER_SERVICE_TOKEN || "orca_test_token_12345";

        const response = await fetch(DEPLOYER_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${DEPLOYER_TOKEN}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                agentId: agentId,
                repoUrl: repoUrl,
                branch: branch
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Deployer error: ${errorText}`);
        }

        const result = await response.json();
        return { success: true, ...result };

    } catch (error: any) {
        console.error("[0rca-Deployer] GitHub Import Failure:", error.message);
        return { success: false, error: error.message };
    }
}
