"use server"

import JSZip from "jszip"

export interface AgentConfig {
    name: string;
    description: string;
    greeting: string;
    cdcApiKey?: string;
    cdcPrivateKey?: string;
    transferLimit?: string;
    timeout?: string;
    googleApiKey?: string;
    vaultAddress?: string;
    tools?: any[];
}

export async function deployCDCAgent(agentId: string, config: AgentConfig) {
    try {
        console.log(`\n[0rca-Deployer] Start CDC Agent: ${agentId}`)

        // 1. Generate agent.py
        const agentCode = generateCDCAgentCode(agentId, config)

        // 2. Create Zip
        const zip = new JSZip()
        zip.file("agent.py", agentCode)

        let requirements = `orca-network-sdk>=1.0.5\npython-dotenv\ncrypto-com-agent-client\n`
        zip.file("requirements.txt", requirements)
        zip.file(".env", "# Generated by 0rca-pod-v2\n")
        zip.file("Procfile", "web: python agent.py\n")

        const zipBlob = await zip.generateAsync({ type: "uint8array" })

        // 3. Prepare Deployment
        const DEPLOYER_URL = "https://deploy.0rca.live/deploy"
        const DEPLOYER_TOKEN = process.env.DEPLOYER_SERVICE_TOKEN || "orca_test_token_12345"

        // Use standard Fetch with Blob/FormData - Note: in Node/Next Server Actions, we need a special way to handle this
        // but typically fetch and FormData are available.
        const formData = new FormData()
        const zipFile = new Blob([zipBlob as any], { type: 'application/zip' })
        formData.append('file', zipFile, 'agent.zip')
        formData.append('agentId', agentId)

        const envVars = [
            { key: 'GOOGLE_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'GEMINI_API_KEY', value: config.googleApiKey || process.env.GOOGLE_API_KEY },
            { key: 'CDC_API_KEY', value: config.cdcApiKey },
            { key: 'CDC_PRIVATE_KEY', value: config.cdcPrivateKey },
            { key: 'ORCA_NETWORK', value: 'mainnet' }
        ].filter(v => v.value);

        formData.append('envVars', JSON.stringify(envVars))

        const response = await fetch(DEPLOYER_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${DEPLOYER_TOKEN}`
            },
            body: formData
        })

        if (!response.ok) {
            const errorText = await response.text()
            throw new Error(`Deployer error: ${errorText}`)
        }

        const result = await response.json()
        return { success: true, ...result }

    } catch (error: any) {
        console.error("[0rca-Deployer] Critical Failure:", error.message)
        return { success: false, error: error.message }
    }
}

function generateCDCAgentCode(agentId: string, config: AgentConfig) {
    const name = config.name || agentId
    const model = "gemini/gemini-2.0-flash"
    const systemPrompt = config.description || "You are a helpful AI assistant."
    const vaultAddress = config.vaultAddress || ""

    let code = `import os
import sys
from dotenv import load_dotenv
from orca_agent_sdk import CryptoComAgent

# Load environment variables
load_dotenv()

def main():
    # Configuration from environment
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        api_key = os.getenv("GEMINI_API_KEY")
    
    # Initialize tools list
    tools = ${JSON.stringify(config.tools || [])}

    # Initialize the Crypto.com Agent (x402 + CDC Backend)
    agent = CryptoComAgent(
        name="${name}",
        model="${model}",
        vault_address="${vaultAddress}",
        provider_api_key=api_key,
        
        # CDC Configuration
        cdc_api_key=os.getenv("CDC_API_KEY"),
        cdc_private_key=os.getenv("CDC_PRIVATE_KEY"),
        
        # Advanced Config
        transfer_limit=${config.transferLimit || -1},
        timeout=${config.timeout || 60},
        
        # Instructions
        instructions="""${systemPrompt}""",
        
        # Custom Tools
        tools=tools
    )
    print(f"[{agent.name}] Initialized Crypto.com Agent.")
    print(f"[{agent.name}] Local Identity: {agent.vault_address}")
    
    # Start the Server
    port = int(os.getenv("PORT", 8080))
    agent.run(host="0.0.0.0", port=port)

if __name__ == "__main__":
    main()
`
    return code
}
