export const agents = [
  { id: '1', name: 'DataViz Pro', developer: 'AlgoLabs', credits: '50', category: 'Data Analysis', tags: ['Analytics', 'Visualization'], executedJobs: 1247, avgTime: '2.3s', description: 'Advanced data visualization and analysis agent', overview: 'Transform complex datasets into actionable insights', problem: 'Manual data analysis is time-consuming and error-prone', solution: 'Automated analysis with real-time visualization' },
  { id: '2', name: 'ContentGen AI', developer: 'CreativeDAO', credits: '75', category: 'Content Creation', tags: ['Writing', 'Marketing'], executedJobs: 892, avgTime: '1.8s', description: 'AI-powered content generation for marketing', overview: 'Create engaging content at scale', problem: 'Content creation bottlenecks slow marketing campaigns', solution: 'Instant, high-quality content generation' },
  { id: '3', name: 'CodeReview Bot', developer: 'DevTools Inc', credits: '100', category: 'Development', tags: ['Code', 'QA'], executedJobs: 2103, avgTime: '3.1s', description: 'Automated code review and quality assurance', overview: 'Maintain code quality standards automatically', problem: 'Manual code reviews are inconsistent', solution: 'AI-powered code analysis and suggestions' },
  { id: '4', name: 'Market Analyzer', developer: 'FinTech Labs', credits: '120', category: 'Finance', tags: ['Trading', 'Analytics'], executedJobs: 1567, avgTime: '1.5s', description: 'Real-time market analysis and predictions', overview: 'Stay ahead of market trends', problem: 'Market data is overwhelming', solution: 'Intelligent pattern recognition and alerts' },
  { id: '5', name: 'Social Sentinel', developer: 'MediaWatch', credits: '60', category: 'Social Media', tags: ['Monitoring', 'Analytics'], executedJobs: 3421, avgTime: '0.9s', description: 'Social media monitoring and sentiment analysis', overview: 'Track brand mentions and sentiment', problem: 'Manual social monitoring is impossible at scale', solution: 'Automated sentiment tracking across platforms' },
  { id: '6', name: 'Image Enhancer', developer: 'PixelPerfect', credits: '85', category: 'Media', tags: ['Images', 'AI'], executedJobs: 987, avgTime: '2.7s', description: 'AI-powered image enhancement and restoration', overview: 'Professional image quality instantly', problem: 'Image editing requires expertise', solution: 'One-click professional enhancement' },
  { id: '7', name: 'Translation Pro', developer: 'LinguaAI', credits: '45', category: 'Language', tags: ['Translation', 'NLP'], executedJobs: 5632, avgTime: '1.2s', description: 'Multi-language translation with context awareness', overview: 'Break language barriers', problem: 'Translation loses context and nuance', solution: 'Context-aware AI translation' },
  { id: '8', name: 'SEO Optimizer', developer: 'RankBoost', credits: '95', category: 'Marketing', tags: ['SEO', 'Analytics'], executedJobs: 1876, avgTime: '2.1s', description: 'Comprehensive SEO analysis and optimization', overview: 'Improve search rankings', problem: 'SEO is complex and constantly changing', solution: 'Automated SEO recommendations' },
];

export const jobs = [
  { id: 'job-1', agentId: '1', name: 'Q4 Sales Analysis', status: 'Completed', date: '2024-01-15', txnId: 'TXN-ABC123', inputHash: 'QmX...789', resultHash: 'QmY...456', input: '{"dataset": "sales_q4.csv", "metrics": ["revenue", "growth"]}', result: '{"revenue": "$2.4M", "growth": "23%", "charts": ["chart1", "chart2"]}' },
  { id: 'job-2', agentId: '1', name: 'Customer Segmentation', status: 'Demo', date: '2024-01-14', txnId: 'TXN-DEF456', inputHash: 'QmA...123', resultHash: 'QmB...789', input: '{"dataset": "customers.csv", "segments": 5}', result: '{"segments": ["segment1", "segment2"], "insights": ["insight1"]}' },
  { id: 'job-3', agentId: '1', name: 'Market Trends', status: 'Hiring', date: '2024-01-13', txnId: 'TXN-GHI789', inputHash: 'QmC...456', resultHash: 'QmD...123', input: '{"timeframe": "30d", "markets": ["crypto", "stocks"]}', result: '{"status": "Processing..."}' },
];
